[package]
name = "watchr"
version = "0.1.0"
edition = "2021"
authors = ["Amanjeev Sethi <aj@amanjeev.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
